### PR TITLE
Forward fix from old stable 2017-01-24

### PR DESCRIPTION
**Pull request by clearkimura**
I have made initial commits to local branch `forkout` in "old stable" that include some fixes since late October 2016 to this date. So that official fork might share some fixes as well.

@kamilion 
Note that I have not (and will not) make changes to files that requires your attention. Some files such as `debian/changelog` and changes log in top level of repository in fork, are both related to program and package versioning, which you should decide for fork counterpart.

This may be discussed in kamilion#2 at anytime later.

### CODE REVIEW

**Comment by kamilion** [comment]
blabbed a bit in the debian changelog as suggested, still pondering changing the mainline ChangeLog

**Comment by kamilion** [comment]
Couldn't sleep, so I ported customizer to PyQt5.
https://github.com/kamilion/customizer/commit/e64c6e6bb762c72ea3fce27e57a82ffa5ade33ba
Give it a shot, if you have a chance.

**Comment by clearkimura** [comment]
@kamilion 
I think it's more relevant to ask for feedback from end users of official fork.

Create a new issue with relevant title in fork's GitHub issues. We used to do similarly for "old stable" (clearkimura#73). I could barely recall just one relevant feedback from end user (clearkimura#75) and the rest are probably just between me and @fluxer in late-2014.

**Comment by kamilion** [comment]
@clearkimura Ugh, I was never notified you were making new releases without me at the old repo. Guess I'll remove my 4.1.2 release.

**Pull request merged**
