### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by perguth**
Provided the combined install command for convenience.

### CODE REVIEW

**Comment by perguth** [comment]
Maybe also include `qt4-linguist-tools` right away (Issue #85)?

**Comment by ghost** [comment]
@pguth 
Thanks again for your suggestion.

I had revised the Wiki some time ago, and the dependency has been included already in the instructions on both--[First guide](https://github.com/clearkimura/Customizer/wiki/First-guide) (for `dpkg` method) and [Installation](https://github.com/clearkimura/Customizer/wiki/Installation) (for alternative methods) pages.

Since you had already include a link to the First guide page, perhaps adding the missing dependency `qt4-linguist-tools` under "REQUIREMENTS" in the README.md would suffice.

**Comment by ghost** [comment]
As for the install command, there is an error in your commit (`sudo apt-get install` appeared twice--why?).

You can either copy the correct install command from [point no. 2 of First guide](https://github.com/clearkimura/Customizer/wiki/First-guide#2-how-to-install-customizer), or for your convenience, I have copy-pasted as below:

`sudo apt-get install git build-essential fakeroot make binutils g++ python python-dev python-qt4 pyqt4-dev-tools squashfs-tools xorriso x11-xserver-utils xserver-xephyr qemu-kvm dpkg-dev debhelper qt4-dev-tools qt4-linguist-tools --no-install-recommends`

The `--no-install-recommends` is included because some user wants to install only minimal packages. Whether you want to include or not in the README.md, is up to you.

**Comment by perguth** [comment]
@clearkimura Just swapped my `apt-get` line for yours. Thanks!

**Pull request merged**
