### PR TITLE
Revert "Altered the way the rebuild script handled kernels and checks…

### PR DESCRIPTION
**Pull request by ghost**
Reverts clearkimura/Customizer#108

Found the first issue with this pull request: The rebuild would fail with Xubuntu official ISO image (I have used 14.04 release). Below is the screenshot when the error occured.

c411-rebuild-error-critical

The error dialog has no exception message at all, but the output in Terminal gave hints that `md5sum.txt` file creation has failed and rebuild was aborted (no ISO image will be created).

> As a fix for ubuntu-mini-remix's integrity check, a SHA256SUMS file will be regenerated if found.

The fix intended for UMR has actually broke the rebuild capability for official ISO images. Not sure why official Lubuntu 64-bit was able to be rebuilded? 

P.S.: Waiting for @kamilion reply; If this takes some time to fix, may be better to revert changes?

### CODE REVIEW

**Comment by ghost** [comment]
Oh, wait.. May be not the pull request fault.. I am testing with even earlier commit d9877c4 also cannot rebuild Xubuntu official ISO image.. Need some time to track since when this was broken.. or why is broken only on my side (32-bit)?

**Update** My last successful build for Xubuntu 14.04 official ISO image on 32-bit host system was commit bb21e29 . Still finding the point where it became broken..

**Comment by kamilion** [comment]
Roger, downloading UMR 14.04.1 amd64 and x86, and xubuntu 32/64 so I can test.

Was this a full unpack/rebuild cycle on a fresh VM?
Can you turn the debug messages on in lib/message.py and lemme know where it hangs?

**Comment by kamilion** [comment]
Oh holy smokes. No wonder everything is going crazy.
The chroot mounting/unmounting is WAY WAY broken, both in theory and in practice...

I have _NO_ idea why lubuntu's so tolerant, but things are going insane in the host system when I'm trying other images.

_ties a rope to the pier_  Time to dive in and figure out why...

**Comment by kamilion** [comment]
I've patched in a bunch of debug messages, my initial instinct that the umount unwind was 'wrong' doesn't seem to be the case -- but I definitely have noticed something weird.

The command line version hasn't exhibit the chroot issues... 
So far, only seems to be the GUI version, and it seems like it occurs when it pops a new terminal window open.

Could very well be a race condition, I've been sprinkling sleep calls in while I debug, it was closing the terminal window.

Still tracking...

**Comment by kamilion** [comment]
I think the issue might end up being gnome-terminal being rearchitected somewhere in the 15.xx series and a race condition with /dev/pts mount/unmount events.

I've also noticed vmware tools has been meddling in systemd's mounts, so when I boot my VM, I ask it to resize my desktop (the only reason I had vmware-tools around) and then kill the user process, and service vmware-tools stop to end the system daemon.

I've added a bunch of debugging output, try a checkout from my repo with this revision.
https://github.com/kamilion/customizer/commit/b3f9e6eda5b4ca01c41ab39be775b83e1b08edf5

Debug messages are forced on, and a number of additional messages have been sprinkled into misc.py.

I'll flush my repo once we've resolved this, since I didn't pull from master before commiting.
Once we figure out where the issue is, we can cherrypick changes.

**Comment by kamilion** [comment]
Okay, so, from my lubuntu 15.10 amd64 VM, I was able to update & rebuild the following ISOs without a problem:

lubuntu-15.10-beta1-desktop-amd64.iso
lubuntu-15.10-beta1-desktop-i386.iso
lubuntu-15.04-desktop-amd64.iso
lubuntu-15.04-desktop-i386.iso
lubuntu-14.10-desktop-amd64.iso
lubuntu-14.10-desktop-i386.iso
lubuntu-14.04.3-desktop-amd64.iso
lubuntu-14.04.3-desktop-i386.iso
ubuntu-mini-remix-15.04-amd64.iso
ubuntu-mini-remix-15.04-i386.iso
ubuntu-mini-remix-14.04.1-amd64.iso
ubuntu-mini-remix-14.04.1-i386.iso
xubuntu-15.10-beta1-desktop-amd64.iso
xubuntu-15.10-beta1-desktop-i386.iso
xubuntu-15.04-desktop-amd64.iso
xubuntu-15.04-desktop-i386.iso
xubuntu-14.04.3-desktop-amd64.iso
xubuntu-14.04.3-desktop-i386.iso

I performed the following actions in each:
apt update
apt full-upgrade

and rebuilt, resulting in a successful ISO, from ~60MB-200MB shrinkage.
(xubuntu 15.10 b1 had the biggest shrink)

I'm now installing from xubuntu 14.04.3-i386 and will attempt to build from there.

**Comment by kamilion** [comment]
Okay, I'm seriously confused now.

Here's my build logs for Ubuntu Mini Remix 14.04.1 32bit:
http://files.sllabs.com/files/long-term/downloads/customizer/logs/buildlog-umr-14.04.txt

And my build logs for xUbuntu 14.04.3 32bit:
http://files.sllabs.com/files/long-term/downloads/customizer/logs/buildlog-xub-14.04.txt

Both were performed from the GUI resulting in successful builds, from an xubuntu 14.04.3 32bit VM on VMWare ESXi 5.5u1.

**Comment by kamilion** [comment]
Added some more debugging output.

https://github.com/kamilion/customizer/commit/7552d171dba0a341df488beb0d42873342fb77ed
https://github.com/kamilion/customizer/commit/e6baf615f3341f33678251031e8f03772d4a29b6

Maybe a good idea to pull into main, track down weird issues people are having...

Here's a complete buildlog from my 15.10 run, including a 'oops, crap, cleanup and start over' event.
http://files.sllabs.com/files/long-term/downloads/customizer/logs/buildlog-lub-15.10.txt

**Comment by ghost** [comment]
Some replies from earlier comments..

> Was this a full unpack/rebuild cycle on a fresh VM?

No, my test machine is a physical i686 circa-2005 single-core machine (yeah, it's quite aged and takes time for testing). My test system is running Xubuntu 14.04 32-bit, with security updates applied.

> Can you turn the debug messages on in lib/message.py and lemme know where it hangs?

Not now.. Perhaps after I my testing method has finished or meets dead end.. I was testing last night while sleepy, so I now redo the testing by checking all other possible factors properly (simple checking like whether my machine has enough RAM; free disk space, etc.).

> The command line version hasn't exhibit the chroot issues...
> So far, only seems to be the GUI version, and it seems like it occurs when it pops a new terminal window open.

I haven't tried with command line; I always try GUI first. Prior to rebuilding, I did open Terminal and did simple checking (run `uname -a` then `exit`); I had no issue for the final ISO rebuilding (at least for UMR 14.04 32-bit image).

> Okay, so, from my lubuntu 15.10 amd64 VM, I was able to update & rebuild the following ISOs without a problem

On my Xubuntu 14.04 32-bit test system, I had rebuilded for:
- UMR 14.04 32-bit ISO image (using gzip compression) -- OK
- UMR 14.04 32-bit ISO image (using xz compression) -- OK

But since you have already tested for 32-bit releases as well, now I suspect my test machine's fault, because there is 50-50 chances that my machine will introduce error due to something trivial (when running heavy task like rebuilding ISO, anything could go wrong on a used 10-year old machine).

**Comment by ghost** [comment]
> Added some more debugging output.
> kamilion@7552d17

Latest commit from your repo has returned `IndentationError` from `File "/usr/sbin/customizer-gui", line 307` when trying to run `sudo customizer-gui`.

I will try the earlier commit kamilion@b3f9e6e instead.

**Update** Now trying to rebuild Xubuntu 14.04 32-bit ISO image, using the earlier commit of yours with debug messages enabled. Will take some time..

**Comment by kamilion** [comment]
https://github.com/kamilion/customizer/commit/e6baf615f3341f33678251031e8f03772d4a29b6
had the indentation fix, I missed one line at the bottom.

**Comment by kamilion** [comment]
Y'know, from your machine description, I think I have an idea of what might have occured... Running out of memory while trying to md5sum filesystem.squashfs is a likely candidate.

**Comment by ghost** [comment]
And I just finished rebuilding with the earlier commit of yours.. I had pasted the Terminal output at this gist https://gist.github.com/clearkimura/2b8c02e3f3993a159fee

>  Running out of memory while trying to md5sum filesystem.squashfs is a likely candidate.

I also suspect this reason, but why now? I have been using this same machine to test Customizer new commits and one random day, suddenly RAM is not enough?

So the rebuild still failed with Xubuntu 14.04 ISO image (only on my side). Meanwhile, I will try again somehow using other way.

**Comment by kamilion** [comment]
yep, bingo.

  => MD5 Checksumming: /home/ISO/casper/filesystem.squashfs
  => Listing files in: /home/FileSystem/usr/share/xsessions

So it bailed on updating the checksums. We must be using more ram than before.
I just did a test on my local box and htop hovered around 917MB used while building.

**Comment by kamilion** [comment]
Give it a shot after creating a temporary swapfile:

``` bash
sudo touch /swapfile
sudo dd if=/dev/zero of=/swapfile bs=1M count=1024
mkswap -c /swapfile
sudo swapon /swapfile
```

count is in megabytes; that'll make a 1GB swapfile.

**Comment by kamilion** [comment]
Gimme a little while, and I'll rejigger how the checksumming works by shelling out of process to md5sum/sha1sum/sha256sum (as they use very little memory)

**Comment by ghost** [comment]
I found the fault on my test machine--something had turned off my 2GB swap. Probably messed up while setting up multiboot system on other logical partitions. My bad, it's my side only!

**Update** My original UUID for swap partiton was different than current ones. Probably rebuild will be successful as usual, once I turned on the swap properly.

**Comment by kamilion** [comment]
Well, turn it back off, and try the latest commit in my repo... We now have chunked hashing, resolving that lonely fixme...  (It was easier than shelling out...)

I'm waiting on the first build to test.

https://github.com/kamilion/customizer/commit/6972dbb6445fdacebf19befc4486cd52f2d2224a

Belay that; messed up, need to import hashlib in the right place. Derp.

https://github.com/kamilion/customizer/commit/e1f609e6b90b3198ede06855eaefaba877a7e867

Trying the build again...

Failed to hash the final iso...

Another commit on the way... ( Do these edit in real time for other people? )

https://github.com/kamilion/customizer/commit/ac22db49bcb9d78da4edae66e35fed40f95d9e32

Trying the build a third time...

Success!

**Comment by kamilion** [comment]
Allrighty, https://github.com/kamilion/customizer/commit/ac22db49bcb9d78da4edae66e35fed40f95d9e32 should work for you with swap disabled. (and debug messages maxed) Give it a shot! :D

Here's the most recent, with the debug messages toned WAY down to only chroots entry/exits.
https://github.com/kamilion/customizer/commit/efa5629cd52155e44568f20d6e743d5ced49e839

And this one I call 'ready' for upstream, with debugging off.
https://github.com/kamilion/customizer/commit/1250cb147f12f93ea88eb2ef4807372fc8decc5b

Anything else you can point out before I submit a new PR?

**Comment by ghost** [comment]
@kamilion 

> Another commit on the way... ( Do these edit in real time for other people? )

Supposedly, yes. Then again, not everyone is logged into GitHub and browsing the same issue thread while you edit or post something at same time. As a result, it is not quite a "real time" for my case.

> Allrighty, kamilion@ac22db4 should work for you with swap disabled. (and debug messages maxed) Give it a shot! :D

Okay, trying out now..

**Comment by kamilion** [comment]
Just patched in a last little goodie I just remembered adding to ubuntu-builder a while back:
Writing "exit 101" to /usr/sbin/policy-rc.d to inhibit APT from spawning processes when packages are installed.
Some documentation here on how this works:
https://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/

Some notes on changes I made: To resolve the problems I was having with the terminal, I added a last terminal to check for, x-terminal-emulator, which will invoke debian's alternatives system to select the terminal the user has expressed a preference for. 

Make sure your /etc/alternatives/x-terminal-emulator is linked to the terminal you'd like customizer to use. 

``` bash
update-alternatives --list x-terminal-emulator
```

will list known terminals, and

``` bash
update-alternatives --config x-terminal-emulator
```

will display a list for you to choose a new one you prefer better.

gnome-terminal seems to be having issues after it's split into a backend/frontend process and which method was used as elevation to root -- pkexec, gksudo, or sudo.
pkexec seems to work best on older releases like 14.04, but fails on 15.10 with Xmir :0.0 errors.
gksudo seems to work on 15.04 and 15.10, but xubuntu doesn't have the gksu package.

This hopefully should be the last round for this patch series. :D
https://github.com/kamilion/customizer/commit/92e7adf1a1a95dc25313cc96926c00023bd9af6e
Implements creation and deletion of /usr/sbin/policy-rc.d while chrooted.

**Comment by ghost** [comment]
@kamilion 
Hurrah! I had success rebuilding Xubuntu 14.04 32-bit ISO image (rebuild filesize is about 970 MB) on my old machine, 1GB RAM with swapoff.

The improvement is significant:
- when using kamilion@b3f9e6e to rebuild ISO, I was using 850 MB RAM + 1001 MB swapon
- when using kamilion@ac22db4 to rebuild ISO, I was using only 311 MB RAM + 0MB swapoff

In both cases, the peak usage of RAM was when doing MD5 checksum (after the creation of filesystem.squashfs). The RAM and swap usage was seen from `htop` that was running beside Customizer and its Terminal.

I have also tested the rebuild ISO image as Live CD in VirtualBox OSE. I ran `integrity-check` and it returned no error (perfect). This is another improvement, since I was getting several errors when doing the check with earlier rebuilds (few months ago). Live CD can be booted normally.

> Anything else you can point out before I submit a new PR?

At this point, I have not found any critical issues..

I am yet to try the latest kamilion@92e7adf on my side. For the latest goodies, what difference should I expect to see as an end-user? Like, less CPU usage or process takes less resources when running APT in chroot (since you mentioned "inhibit spawing processes")?

**Comment by ghost** [comment]
Anyway, I shall close this pull request since my report was invalid.

**Comment by kamilion** [comment]
Awesome!

htop is a bit more useful when -d 3 or -d 5 is passed to increase the update rate.
(but on your rig, this might eat too much CPU)

As for the inhibiting thing, it prevents apt from starting services when inside the chroot.
Say, for example, a hook installs mysql, apt will normally try to start mysqld right then and there, but if the policy-rc.d file is around, instead you'll see

```
invoke-rc.d: policy-rc.d denied execution of start.
```

instead of starting the service (while in the chroot) which can cause some weird problems.
(like thermald running when customizer reinstalls the kernel.)

**Comment by ghost** [comment]
> Say, for example, a hook installs mysql, apt will normally try to start mysqld right then and there, but if the policy-rc.d file is around,

Good example, easy to understand!

**Comment by kamilion** [comment]
Right now I'm trying a run with 'python2 -3 customizer-gui' to see where it complains.
After all the cleaning I did switching % out for .format() calls, it seems like there's only one or two tiny spots to be fixed to end up python3-clean for 2.7 and 3.4.

If I make good headway on that; I'll commit it, otherwise I'll submit a PR for head shortly with the changes outlined in the above thread without messing around with python3.

**Pull request closed without merging**
